"""Airflow tasks that move YouTube video data from JSON to PostgreSQL.

The pipeline has two layers: the staging task stores raw API values, and the
core task reads that staging data, transforms it, and stores analysis-ready
values in the core schema.
"""

# Read the raw YouTube JSON file generated by the extraction DAG.
from datawarehouse.data_loading import load_data

# Convert raw values (such as ISO 8601 durations) into warehouse-ready values.
from datawarehouse.data_transformation import parse_duration, transform_data

# Reusable SQL operations for adding, updating, and removing table rows.
from datawarehouse.data_modification import delete_rows, insert_rows, update_rows

# PostgreSQL connection and table/schema helper functions.
from datawarehouse.data_utils import (
    close_conn_cursor,
    create_schema,
    create_table,
    get_conn_cursor,
    get_video_ids,
)

# Airflow turns functions decorated with @task into independently observable
# tasks that can be scheduled, retried, and viewed in the Airflow UI.
import logging
from airflow.decorators import task

# Send progress and error messages to each task's Airflow log.
logger = logging.getLogger(__name__)

# The same table name is used in both PostgreSQL schemas: staging.yt_api and
# core.yt_api.
table = "yt_api"


@task
def staging_table():
    """Synchronize today's raw JSON extract with the staging.yt_api table."""

    # Staging is the landing area for the API's original field names and values.
    schema = 'staging'

    # Set defaults before the try block so the finally block can safely decide
    # whether a cursor and connection were successfully opened.
    conn, curr = None, None

    try:
        # Open a dictionary-style PostgreSQL cursor for reading and modifying
        # records. Each fetched row can therefore be accessed by column name.
        conn, curr = get_conn_cursor()
        
        # Load the JSON file written by the upstream `produce_json` DAG.
        YT_data = load_data()

        # Ensure the schema and empty table exist before querying or loading it.
        create_schema(schema)
        create_table(schema)

        # Keep a snapshot of IDs that were already in staging before this run.
        table_ids = get_video_ids(curr, schema)

        for row in YT_data:
            # An empty table means every raw JSON record is new.
            if len(table_ids) == 0:
                insert_rows(curr, conn, schema, row)
            
            else:
                # Existing video IDs are refreshed; newly discovered IDs are
                # added as new rows.
                if row["video_id"] in table_ids:
                    update_rows(curr, conn, schema, row)
                else:
                    insert_rows(curr, conn, schema, row)

        # Build the set of video IDs present in today's source JSON.
        ids_in_json = {row['video_id'] for row in YT_data}

        # An ID in the old table but absent from this extract represents a video
        # that should no longer be retained in staging.
        ids_to_delete = set(table_ids) - ids_in_json

        if ids_to_delete:
            delete_rows(curr, conn, schema, ids_to_delete)
        
        logger.info(f"{schema} table update completed")

    except Exception as e:
        # Log and re-raise errors so Airflow records this task as failed.
        logger.error(f"An error occurred during the update of {schema} table: {e}")
        raise e

    finally:
        # Close database resources even if JSON loading or SQL execution fails.
        if conn and curr:
            close_conn_cursor(conn, curr)


@task
def core_table():
    """Transform staging records and synchronize them with core.yt_api."""

    # Core is the analysis-ready layer, including fields derived during
    # transformation such as `Video_Type`.
    schema = 'core'

    # These defaults allow the finally block to run safely after a failed
    # connection attempt.
    conn, curr = None, None

    try:
        conn, curr = get_conn_cursor()

        # Create the target schema/table on a first run; do nothing if they
        # already exist.
        create_schema(schema)
        create_table(schema)

        # Record which IDs existed in core before this synchronization begins.
        table_ids = get_video_ids(curr, schema)

        # Collect every ID seen in staging so outdated core rows can be found
        # after all current rows have been processed.
        current_video_ids = set()

        # Read the raw, already-loaded records from the staging layer. The core
        # task deliberately uses staging instead of reopening the JSON file.
        curr.execute(f"SELECT * FROM staging.{table}")
        rows = curr.fetchall()

        for row in rows:
            # Track this video as active in the current source snapshot.
            current_video_ids.add(row["Video_ID"])

            # Transform ISO duration and derive Video_Type before inserting the
            # record into the final table.
            if len(table_ids) == 0:
                transformed_row = transform_data(row)
                insert_rows(curr, conn, schema, transformed_row)

            else:
                transformed_row = transform_data(row)
                # Refresh an existing core record, or insert a video that is
                # present in staging for the first time.
                if transformed_row["Video_ID"] in table_ids:
                    update_rows(curr, conn, schema, transformed_row)
                
                else:
                    insert_rows(curr, conn, schema, transformed_row)

        # Existing core IDs not observed in staging are stale and are removed.
        ids_to_delete = set(table_ids) - current_video_ids

        if ids_to_delete:
            delete_rows(conn, curr, schema, ids_to_delete)

        logger.info(f"{schema} table update completed")

    except Exception as e:
        # Surface failures to Airflow after preserving context in the task log.
        logger.error(f"An error occurred during the update of {schema} table: {e}")
        raise e
    
    finally:
        # Always release the database cursor and connection for this task.
        if conn and curr:
            close_conn_cursor(conn, curr)




